"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";

const nav = [{ href: "/studio", label: "Criar" }, { href: "/library", label: "Biblioteca" }, { href: "/brand", label: "Minha marca" }, { href: "/planning", label: "Planejamento" }];

export function ProductSidebar({ active }: { active: string }) {
  return <aside className="cria-product-sidebar"><Link href="/" className="cria-sidebar-mark"><span className="cria-mark-dot" /><span>cr<span>IA</span></span></Link><nav>{nav.map((item, index) => <Link key={item.href} className={active === item.label ? "is-active" : ""} href={item.href}><span>{["✦", "▦", "◒", "⌁"][index]}</span>{item.label}</Link>)}</nav><div className="cria-sidebar-bottom"><div className="cria-sidebar-profile"><Image src="/emporio-aurora-logo.jpeg" alt="Logo do Empório Aurora" width={34} height={34} /><div><b>Empório Aurora</b><small>Plano Essencial</small></div><i>•••</i></div></div></aside>;
}

function ProductHeader({ active }: { active: string }) {
  return <><ProductSidebar active={active} /><header className="cria-product-header"><Link href="/" className="cria-landing-mark"><span className="cria-mark-dot" /><span>cr<span>IA</span></span></Link><div className="cria-product-context">Empório Aurora <b>/</b> {active.toLowerCase()}</div><div className="cria-product-user"><span>EA</span><b>Empório Aurora</b><i>⌄</i></div></header></>;
}

const campaigns = [
  { title: "Café Aurora Especial", type: "Campanha", date: "Hoje, 14:32", color: "yellow", text: "sua manhã pede algo especial.", status: "Pronta" },
  { title: "Dia dos Pais", type: "Post", date: "Hoje, 13:08", color: "orange", text: "o melhor presente é estar perto.", status: "Rascunho" },
  { title: "Torra local · lote novo", type: "Story", date: "Ontem, 17:45", color: "cyan", text: "aroma que chega primeiro.", status: "Pronta" },
  { title: "Kit presente de inverno", type: "Carrossel", date: "12 ago, 09:20", color: "blue", text: "feito para compartilhar.", status: "Pronta" },
];

export function LibraryPage() {
  const [filter, setFilter] = useState("Tudo");
  const visible = filter === "Tudo" ? campaigns : campaigns.filter((campaign) => campaign.type === filter);
  return <main className="cria-product-page"><ProductHeader active="Biblioteca" /><section className="cria-page-inner"><div className="cria-page-heading"><div><p className="cria-kicker"><i /> seu acervo de ideias</p><h1>Biblioteca</h1><p>Campanhas, posts e histórias que a sua marca já colocou no mundo.</p></div><Link className="cria-primary-cta" href="/studio">Criar algo novo <span>→</span></Link></div><div className="cria-library-toolbar"><div className="cria-library-filters">{["Tudo", "Campanha", "Post", "Story", "Carrossel"].map((item) => <button type="button" className={filter === item ? "is-active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><button className="cria-search" type="button">⌕ <span>Buscar criações</span></button></div><div className="cria-campaign-grid">{visible.map((campaign) => <article className="cria-library-card" key={campaign.title}><div className={`cria-library-art is-${campaign.color}`}><small>{campaign.type} · {campaign.status}</small><strong>{campaign.text}</strong><span>{campaign.title.split(" ").slice(-1)[0]}</span></div><div className="cria-library-card-info"><div><h3>{campaign.title}</h3><p>{campaign.date}</p></div><button type="button" aria-label={`Mais opções para ${campaign.title}`}>•••</button></div></article>)}</div></section></main>;
}

export function BrandPage() {
  const [saved, setSaved] = useState(false);
  return <main className="cria-product-page"><ProductHeader active="Minha marca" /><section className="cria-page-inner cria-brand-page"><div className="cria-page-heading"><div><p className="cria-kicker"><i /> o que guia tudo</p><h1>Minha marca</h1><p>O brandbook que a crIA usa para criar com o seu jeito.</p></div><button className="cria-primary-cta" type="button" onClick={() => setSaved(true)}>{saved ? "Alterações salvas ✓" : "Salvar alterações"}</button></div><div className="cria-brand-layout"><aside className="cria-brand-summary"><div className="cria-brand-avatar">A</div><h2>Empório Aurora</h2><p>Café especial · negócio local</p><div className="cria-brand-score"><span>Marca pronta</span><strong>92%</strong><i><b /></i></div><Link href="/onboarding">Atualizar fontes →</Link></aside><div className="cria-brand-fields"><section><div className="cria-field-heading"><span>01</span><div><h3>Essência</h3><p>As palavras que definem o seu negócio.</p></div></div><div className="cria-brand-input-grid"><label>Nome da marca<input defaultValue="Empório Aurora" /></label><label>Segmento<input defaultValue="Café especial e produtos locais" /></label><label className="is-wide">Posicionamento<textarea defaultValue="Um empório próximo, que transforma café fresco e produção local em momentos para compartilhar." /></label></div></section><section><div className="cria-field-heading"><span>02</span><div><h3>Voz e personalidade</h3><p>Como a sua marca fala com as pessoas.</p></div></div><div className="cria-tone-list"><button type="button" className="is-active">Acolhedora</button><button type="button" className="is-active">Próxima</button><button type="button" className="is-active">Confiante</button><button type="button">Divertida</button><button type="button">Sofisticada</button></div><label className="cria-brand-label">Não fazemos <input defaultValue="Promessas exageradas, clichês ou linguagem distante." /></label></section><section><div className="cria-field-heading"><span>03</span><div><h3>Direção visual</h3><p>O universo que aparece nas suas peças.</p></div></div><div className="cria-color-row"><span className="cria-color-swatch is-blue" /><span className="cria-color-swatch is-yellow" /><span className="cria-color-swatch is-orange" /><span className="cria-color-swatch is-paper" /><div><b>Azul Aurora</b><small>Paleta principal · 4 cores</small></div></div></section></div></div></section></main>;
}

export function PlanningPage() {
  return <main className="cria-product-page"><ProductHeader active="Planejamento" /><section className="cria-page-inner"><div className="cria-page-heading"><div><p className="cria-kicker"><i /> conteúdo com intenção</p><h1>Planejamento</h1><p>Uma visão simples do que a sua marca pode dizer nesta semana.</p></div><Link className="cria-primary-cta" href="/studio">Criar campanha <span>→</span></Link></div><div className="cria-planning-board"><div className="cria-week-heading"><button type="button">←</button><div><b>agosto 2026</b><span>semana 34 · 17 — 23</span></div><button type="button">→</button></div><div className="cria-week-grid">{["seg 17", "ter 18", "qua 19", "qui 20", "sex 21", "sáb 22", "dom 23"].map((day, index) => <div className={`cria-day-column ${index === 2 ? "is-today" : ""}`} key={day}><span>{day}</span>{index === 2 ? <article className="cria-plan-card is-blue"><small>hoje · post</small><b>Dia dos Pais</b><p>o melhor presente é estar perto.</p></article> : null}{index === 4 ? <article className="cria-plan-card is-yellow"><small>sexta · story</small><b>Torra fresca</b><p>lote novo chegando.</p></article> : null}{index === 6 ? <button className="cria-empty-plan" type="button">+ adicionar</button> : null}</div>)}</div></div><div className="cria-planning-note"><span>✦</span><p><b>Uma sugestão da crIA</b><br />Você ainda não falou sobre a produção local esta semana. É um bom momento para aproximar a marca da sua cidade.</p><Link href="/studio">Criar a partir disso →</Link></div></section></main>;
}
